<a href="https://colab.research.google.com/github/Madhuvod/AI-Rover/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.0+cu121'

In [2]:
#import torch
#print("CUDA available:", torch.cuda.is_available())
#print("Current device:", torch.cuda.get_device_name(0))

In [3]:
!nvidia-smi

Thu Jul 11 08:58:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [5]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.item()

7

In [8]:
Yessur = torch.tensor([[[3,5, 76],
               [43,9,322],
               [65,1,4],
                [44,3, 0]],[[3,5, 76],
               [43,9,322],
               [65,1,4],
                [44,3, 0]]])

In [9]:
Yessur.shape

torch.Size([2, 4, 3])

In [10]:
dubster = torch.ones([1,4])
dubster

tensor([[1., 1., 1., 1.]])

In [11]:
dubster.dtype


torch.float32

In [12]:
water = torch.arange(start = 69, end=87, step=2)
water

tensor([69, 71, 73, 75, 77, 79, 81, 83, 85])

In [13]:
water_zeros = torch.zeros_like(input=water)
water_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
float_32 = torch.tensor([4,5,22], dtype =None, device=None, requires_grad=False)
float_32

tensor([ 4,  5, 22])

In [15]:
float_16 = float_32.type(torch.half)
float_16

tensor([ 4.,  5., 22.], dtype=torch.float16)

In [16]:
info_tensor = torch.tensor([[3,7,3],
                           [6,88,2]], dtype = torch.half)
info_tensor

tensor([[ 3.,  7.,  3.],
        [ 6., 88.,  2.]], dtype=torch.float16)

In [17]:
print(info_tensor.device, info_tensor.shape, info_tensor.dtype)

cpu torch.Size([2, 3]) torch.float16


In [18]:
tensor = torch.tensor([22, 33, 44])
tensor.size()

torch.Size([3])

In [19]:
tensor + 50

tensor([72, 83, 94])

In [20]:
tensor * 10

tensor([220, 330, 440])

In [21]:
tensor = torch.multiply(tensor,10)
tensor

tensor([220, 330, 440])

In [22]:
#matrix multiplication
matmul_tensor = torch.tensor([3, 6, 9])
matmul_tensor

tensor([3, 6, 9])

In [23]:
kalki = torch.rand(2,3)
kalki


tensor([[0.4968, 0.0385, 0.5577],
        [0.3545, 0.8661, 0.5686]])

In [24]:
kalki.dtype, tensor.dtype

(torch.float32, torch.int64)

In [25]:
kali = torch.tensor([[0.4],[0.2],[0.3]])
torch.matmul(kali , kalki)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 2x3)

In [26]:
tensor_a = torch.tensor([[5, 15, 25,],[23,3,4]])
tensor_b = torch.tensor([[12,33,44],[1,55,2]])
torch.mm(tensor_a, tensor_b.T)

tensor([[1655,  880],
        [ 551,  196]])

In [27]:
djo = torch.arange(0,60,6)
djo, djo.dtype, djo.size()

(tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54]),
 torch.int64,
 torch.Size([10]))

In [28]:
djo.max(), djo.min(), djo.mean(dtype=torch.float32), djo.sum()

(tensor(54), tensor(0), tensor(27.), tensor(270))

In [29]:
djo.argmin(), torch.argmax(djo)

(tensor(0), tensor(9))

In [30]:
x = torch.rand(1, 20, 2)
x, x.shape

(tensor([[[0.5577, 0.3677],
          [0.1098, 0.2838],
          [0.1451, 0.5606],
          [0.1168, 0.7364],
          [0.9112, 0.7489],
          [0.5050, 0.4670],
          [0.8279, 0.6918],
          [0.3799, 0.1944],
          [0.5158, 0.1501],
          [0.1309, 0.1712],
          [0.8513, 0.3358],
          [0.3743, 0.1375],
          [0.4005, 0.6997],
          [0.7901, 0.8434],
          [0.2858, 0.6817],
          [0.4739, 0.7898],
          [0.8293, 0.0525],
          [0.8575, 0.4000],
          [0.6177, 0.7778],
          [0.9564, 0.0116]]]),
 torch.Size([1, 20, 2]))

In [31]:
x_reshaped = x.reshape(2, 20)
x_reshaped

tensor([[0.5577, 0.3677, 0.1098, 0.2838, 0.1451, 0.5606, 0.1168, 0.7364, 0.9112,
         0.7489, 0.5050, 0.4670, 0.8279, 0.6918, 0.3799, 0.1944, 0.5158, 0.1501,
         0.1309, 0.1712],
        [0.8513, 0.3358, 0.3743, 0.1375, 0.4005, 0.6997, 0.7901, 0.8434, 0.2858,
         0.6817, 0.4739, 0.7898, 0.8293, 0.0525, 0.8575, 0.4000, 0.6177, 0.7778,
         0.9564, 0.0116]])

In [32]:
x_view = x.view(2, 20)
x_view

tensor([[0.5577, 0.3677, 0.1098, 0.2838, 0.1451, 0.5606, 0.1168, 0.7364, 0.9112,
         0.7489, 0.5050, 0.4670, 0.8279, 0.6918, 0.3799, 0.1944, 0.5158, 0.1501,
         0.1309, 0.1712],
        [0.8513, 0.3358, 0.3743, 0.1375, 0.4005, 0.6997, 0.7901, 0.8434, 0.2858,
         0.6817, 0.4739, 0.7898, 0.8293, 0.0525, 0.8575, 0.4000, 0.6177, 0.7778,
         0.9564, 0.0116]])

In [33]:
x_stack = torch.randint(2, 12, (2,2))
x_stack, x_stack.shape

(tensor([[ 8,  5],
         [10, 10]]),
 torch.Size([2, 2]))

In [34]:
x_stackk = x_stack.reshape(1,4)
x_stackk

tensor([[ 8,  5, 10, 10]])

In [35]:
x_stackkk = torch.stack([x_stackk,x_stackk], dim=2)
x_stackkk

tensor([[[ 8,  8],
         [ 5,  5],
         [10, 10],
         [10, 10]]])

In [36]:
x_stackkk = torch.stack([x_stackk,x_stackk], dim=1)
x_stackkk

tensor([[[ 8,  5, 10, 10],
         [ 8,  5, 10, 10]]])

In [37]:
dun = torch.rand([2,3,5])
dun, dun.size()

(tensor([[[0.7711, 0.4011, 0.6854, 0.8714, 0.9710],
          [0.9738, 0.4587, 0.8774, 0.8663, 0.7761],
          [0.5397, 0.4978, 0.8521, 0.0961, 0.1219]],
 
         [[0.3761, 0.2974, 0.5101, 0.4269, 0.0443],
          [0.0606, 0.4353, 0.8327, 0.1574, 0.9429],
          [0.4277, 0.4765, 0.8530, 0.0457, 0.6983]]]),
 torch.Size([2, 3, 5]))

In [38]:
dun_permuted = torch.permute(dun, (2,1,0))
dun_permuted, dun_permuted.shape

(tensor([[[0.7711, 0.3761],
          [0.9738, 0.0606],
          [0.5397, 0.4277]],
 
         [[0.4011, 0.2974],
          [0.4587, 0.4353],
          [0.4978, 0.4765]],
 
         [[0.6854, 0.5101],
          [0.8774, 0.8327],
          [0.8521, 0.8530]],
 
         [[0.8714, 0.4269],
          [0.8663, 0.1574],
          [0.0961, 0.0457]],
 
         [[0.9710, 0.0443],
          [0.7761, 0.9429],
          [0.1219, 0.6983]]]),
 torch.Size([5, 3, 2]))

In [39]:
x_index = torch.arange(1,10).reshape(1,3,3)
x_index

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [40]:
x_index[:,2,2]

tensor([9])

In [41]:
x_index[0,:,2]

tensor([3, 6, 9])

In [42]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [49]:
import torch
import random

MANUAL_SEED = 42
torch.manual_seed(seed = MANUAL_SEED)
random_seed_C = torch.rand(3,4)

torch.random.manual_seed(seed = MANUAL_SEED)
random_seed_D = torch.rand(3,4)


random_seed_C, random_seed_D, random_seed_C == random_seed_D


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [50]:
!nvidia-smi


Thu Jul 11 09:30:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
torch.cuda.is_available()

False