# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

veera = torch.rand(7,7)
veera, veera.size()

# Create random tensor


(tensor([[0.7377, 0.3637, 0.6215, 0.2019, 0.0650, 0.9191, 0.9726],
         [0.4582, 0.1463, 0.3073, 0.0502, 0.7232, 0.0433, 0.4815],
         [0.0979, 0.8757, 0.5585, 0.0546, 0.7617, 0.2248, 0.7042],
         [0.2305, 0.9874, 0.5616, 0.4741, 0.8120, 0.4422, 0.8654],
         [0.0899, 0.4796, 0.4380, 0.8107, 0.2411, 0.1938, 0.5481],
         [0.8506, 0.5494, 0.0471, 0.5227, 0.5053, 0.4228, 0.2112],
         [0.1893, 0.3167, 0.2698, 0.1291, 0.0480, 0.2713, 0.8061]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
karna = torch.rand(1,7).T
matmul = torch.matmul(veera, karna)
matmul

# Perform matrix multiplication


tensor([[1.6651],
        [0.8905],
        [1.3052],
        [1.5868],
        [1.0160],
        [0.7258],
        [0.9982]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
import torch
import random

#MANUAL_SEED = 0
torch.manual_seed(seed = 0)

# Create two random tensors
suma = torch.rand(7,7)
ash = torch.rand(1,7).T


# Matrix multiply tensors
matmull = torch.matmul(suma, ash)
matmull, matmull.size()


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed=1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(seed=1234)

# Check for access to GPU
device = "gpu" if torch.cuda.is_available() else "cpu"


# Create two random tensors on GPU
dubs = torch.rand(2,3)
cubs = torch.rand(2,3)
dubs_on_gpu = dubs.to(device)
cubs_on_gpu = cubs.to(device)

device,dubs_on_gpu, cubs_on_gpu


('cpu',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
import torch
cubs_on_gpu = cubs_on_gpu.T
mat = torch.matmul(dubs_on_gpu, cubs_on_gpu)
mat


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
ma = torch.max(mat)

# Find min
mi = torch.min(mat)
ma,mi


(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
maxx = torch.argmax(mat)

# Find arg min
minn = torch.argmin(mat)
maxx,minn


(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
import torch
import random

MANUAL_SEED = 7
torch.manual_seed(seed = MANUAL_SEED)


# Create random tensor
dubster = torch.rand(1,1,1,10)



# Remove single dimensions
dubster_sq = torch.squeeze(dubster)

# Print out tensors and their shapes
dubster, dubster.shape, dubster_sq, dubster_sq.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))